#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

read_branch="$(git rev-parse --abbrev-ref HEAD)"

if [ $read_branch != "master" ]
then
  exit 0
fi

read_latest_tag="$(git describe --abbrev=0 --tags)"
read_npm_version=$(node -p "require('./package.json').version")

if [ $read_latest_tag != $read_npm_version ]
then
  echo "Tag $read_latest_tag does not match version $read_npm_version in package.json. Aborting push and removing tag..."
  git tag -d $read_latest_tag
  echo "Please remember to bump package.json version together with tagging"
  exit 1
fi
