#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

read_branch="$(git rev-parse --abbrev-ref HEAD)"

if [ $read_branch != "master" ]
then
  exit 0
fi

function version { echo "$@" | awk -F. '{ printf("%d%03d%03d%03d\n", $1,$2,$3,$4); }'; }

read_latest_tag="$(git describe --abbrev=0 --tags)"
read_npm_version=$(node -p "require('./package.json').version")

if [ $(version $read_latest_tag) -gt $(version $read_npm_version) ]; then
    echo "Tag $read_latest_tag is higher than version $read_npm_version in package.json. Aborting push and removing tag..."
    git tag -d $read_latest_tag
    echo "Please remember to bump package.json version together with tagging"
    exit 1
fi

if [ $(version $read_latest_tag) -lt $(version $read_npm_version) ]; then
    echo "Tag $read_latest_tag is lower than version $read_npm_version in package.json. Aborting push..."
    echo "Please remember to tag together with bump package.json"
    exit 1
fi
