name: Publish Job
run-name: Publishing 🚀...
on: [push]
jobs:
  lint:
    name: Publishing 🚀...
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Cache node_modules
      id: cache-node-modules
      uses: actions/cache@v3
      env:
        cache-name: cache-node-modules
      with:
        path: node_modules
        key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}

    - name: Build repository
      run: yarn build

    - name: Inject .npmrc
      run: |
        echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > .npmrc
        cat .npmrc
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    # - name: Publish build
    #   run: npm publish
