name: Coverage
run-name: Collecting coverage from '${{ github.ref_name }}' 📰...
on:
  workflow_dispatch: {}
  push:
    branches:    
      - master
jobs:
  dependencies:
    name: Verify dependencies 📦...
    uses: ./.github/workflows/_dependencies.job.yml

  coverage:
    name: Running coverage tests 📰...
    needs: [dependencies]
    uses: ./.github/workflows/_coverage.job.yml
