name: Update
run-name: Updating branch '${{ github.ref_name }}' 🔄...
on:
  workflow_dispatch: {}
  push:
    branches:
      - develop
    paths:
      - "**/yarn.lock"
jobs:
  dependencies:
    name: Verify dependencies 📦...
    uses: ./.github/workflows/_dependencies.job.yml
